services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartparking-sqlserver-container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1434:1433"
    volumes:
      - smartparking_sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartparking-api-container
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=SmartParkingDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  client:
    build:
      context: ./smart-parking-client
      dockerfile: Dockerfile
    container_name: smartparking-client-container
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  smartparking_sql_data: